### ISSUE TITLE
Search filter did not validate for Years/Number of pages (In Third Release)

### ISSUE THREAD

**Issue by Keerththanan** [dilshanth10/LibraryManagementSystem#1]
When we use the search filter, It should be able to validate Years and Integers 
![search1](https://user-images.githubusercontent.com/20047463/44652762-696dd280-aa0a-11e8-9574-6fd7c2d9f280.JPG)

**Proud to find issues in your 3rd Release** ;)

**Comment by dilshanth10** [comment]
Search field cannot be validated. It will restrict the search purpose. And this application is not going to work for mentally disorder person.. Only some common sense person can be able to use this application. Sorry.. we are not creating an AI here.

**Comment by Keerththanan** [comment]
No need of any AI here, What you need is **JUST JAVA SCRIPT VALIDATION**.

That is one of my responsibility **As a Chief QA of SGIC**. 👍

**Comment by dilshanth10** [comment]
search feature doesn't require any validation. if you type the wrong record then you can't get the result. that's all. validation is not required. if i have to put the validation for this kind of issue, then i also have to restrict the entry of text search which doesn't have any records. this is not something to consider as a defect. **Rejected**..
