### ISSUE TITLE
Unable to edit **ANY OF THE BOOK**

### ISSUE THREAD

**Issue by Keerththanan** [dilshanth10/LibraryManagementSystem#2]
![editbook2](https://user-images.githubusercontent.com/20047463/44655525-13515d00-aa13-11e8-81d7-8c4c7d2b4978.JPG)

I can not be able to edit or delete any of the book as per requirement.
###**SMOKE TEST FAILED**

**Comment by dilshanth10** [comment]
This is UI problem.

**Comment by Keerththanan** [comment]
FUNCTIONALITY, You should validate this.

**Comment by dilshanth10** [comment]
It is not functionality issue. It is just UI not good enough to maintain the big record. I may be fix this later.
